[project]
name = "onepm"
description = "Picks the right package manager for you."
authors = [
    {name = "Frost Ming", email = "mianghong@gmail.com"},
]
dependencies = [
    "packaging>=22.1",
    "tomlkit>=0.12.3",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
dynamic = ["version"]
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
shims = ["onepm-shims"]

[project.urls]
Homepage = "https://github.com/frostming/onepm"
Repository = "https://github.com/frostming/onepm"
Changelog = "https://github.com/frostming/onepm/releases"

[project.scripts]
pi = "onepm:pi"
pu = "onepm:pu"
pr = "onepm:pr"
pun = "onepm:pun"
pa = "onepm:pa"
onepm = "onepm.cli:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "scm"
