name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pdm install -dGtest
      - name: Run Tests
        run: |
          pdm run pytest -v tests
