name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install Dependencies
        run: |
          pdm sync
      - name: Run Tests
        run: |
          pdm run test
